apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: mirror-config
spec:
  repositoryDigestMirrors:
  - mirrors:
    - cp.stg.icr.io/cp
    source: cp.icr.io/cp
  - mirrors:
    - cp.stg.icr.io/cp
    source: docker.io/ibmcom
