###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2020. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  name: digitalworker
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: 20.0.2
spec:
  appVersion: 20.0.2
  shared_configuration:
    sc_deployment_patterns: digitalworker
    sc_optional_components:
    sc_deployment_type: demo
    # Possible values OCP,ROKS
    sc_deployment_platform: OCP
    storage_configuration:
      # For ROKS you can use : ibmc-file-gold or ibmc-file-silver value
      sc_dynamic_storage_classname: ""

  #######################################################################
  ########      IBM Automation Digital Worker        ########
  #######################################################################
  adw_configuration:
