###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2020. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  name: icp4adeploy
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: 20.0.2
spec:
  appVersion: 20.0.2

  shared_configuration:
    ## Use this parameter to specify the license for the CP4A deployment and
    ## the possible values are: non-production and production and if not set, the license will
    ## be defaulted to production.  This value could be different from the other licenses in the CR.
    sc_deployment_license: non-production

    ## CP4A patterns or capabilities to be deployed.  The base pattern is "foundation pattern", which includes BAN (Navigator) and RR.
    sc_deployment_patterns: decisions_ads

    ## The optional component for 'decisions_ads' are 'ads_designer' and 'ads_runtime'.
    # In demo mode, both are always installed and set in 'sc_optional_components' list by the user installation script.
    sc_optional_components:

    ## This is the deployment type and the possible values are: demo, non-production, and production.
    sc_deployment_type: demo

    ## This is the version of the OCP/ROKS platform and the possible values are: 3.11, 4.2, and 4.3.  This is usually set by the User script and it is
    ## used by the Operator to determine the version to perform the pre-requisites in order to deploy Db2.
    sc_deployment_platform:

    sc_deployment_hostname_suffix: "{{ meta.name }}"

    storage_configuration:
      ## For OCP 3.11 or 4.x, the storage class will be provided by the user
      ## during the execution of the User script (cp4a-deployment.sh)
      sc_dynamic_storage_classname:

    images:
      keytool_job_container:
        repository: cp.icr.io/cp/cp4a/ums/dba-keytool-jobcontainer
        tag: 20.0.2
      dbcompatibility_init_container:
        repository: cp.icr.io/cp/cp4a/aae/dba-dbcompatibility-initcontainer
        tag: 20.0.2
      keytool_init_container:
        repository: cp.icr.io/cp/cp4a/ums/dba-keytool-initcontainer
        tag: 20.0.2
      umsregistration_initjob:
        repository: cp.icr.io/cp/cp4a/aae/dba-umsregistration-initjob
        tag: 20.0.2
      db2u_tools:
        repository: docker.io/ibmcom/db2u.tools
        tag: 11.5.1.0-CN1
      db2:
        repository: docker.io/ibmcom/db2
        tag: 11.5.1.0-CN1
      db2_auxiliary:
        repository: docker.io/ibmcom/db2u.auxiliary.auth
        tag: 11.5.1.0-CN1
      db2_init:
        repository: docker.io/ibmcom/db2u.instdb
        tag: 11.5.1.0-CN1
      db2_etcd:
        repository: quay.io/coreos/etcd
        tag: v3.3.10
      openldap:
        repository: osixia/openldap
        tag: 1.3.0
      busybox:
        repository: docker.io/library/busybox
        tag: latest
      phpldapadmin:
        repository: osixia/phpldapadmin
        tag: 0.9.0


  ########################################################################
  ########   IBM Business Automation Navigator configuration      ########
  ########################################################################
  navigator_configuration:
    image:
      repository: cp.icr.io/cp/cp4a/ban/navigator-sso
      tag: ga-308-icn

  ########################################################################
  ########      IBM Resource Registry configuration               ########
  ########################################################################
  resource_registry_configuration:
    images:
      resource_registry:
        repository: cp.icr.io/cp/cp4a/aae/dba-etcd
        tag: 20.0.2

  ########################################################################
  ########      IBM Business Automation Studio configuration      ########
  ########################################################################
  bastudio_configuration:
    images:
      bastudio:
        repository: cp.icr.io/cp/cp4a/bas/bastudio
        tag: 20.0.2
    jms_server:
      image:
        repository: cp.icr.io/cp/cp4a/bas/jms
        tag: 20.0.2
    playback_server:
      images:
        db_job:
          repository: cp.icr.io/cp/cp4a/bas/solution-server-helmjob-db
          tag: 20.0.2
        solution_server:
          repository: cp.icr.io/cp/cp4a/bas/solution-server
          tag: 20.0.2

  ########################################################################
  ########   IBM User and Group Management Service configuration  ########
  ########################################################################
  ums_configuration:
    images:
      ums:
        repository: cp.icr.io/cp/cp4a/ums/ums
        tag: 20.0.2


  ########################################################################
  ########   IBM Business Automation Decision Services            ########
  ########################################################################
  ads_configuration:

    decision_designer:
      enabled: true

    decision_runtime:
      enabled: true

    rr_integration:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-rrintegration
        tag: 20.0.2

    front:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-front
        tag: 20.0.2

    download_service:
      ums_enabled: true
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-download
        tag: 20.0.2

    rest_api:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-restapi
        tag: 20.0.2

    git_service:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-gitservice
        tag: 20.0.2

    parsing_service:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-parsing
        tag: 20.0.2

    run_service:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-run
        tag: 20.0.2

    decision_runtime_service:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-runtime
        tag: 20.0.2

