###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2020. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-cp4a-operator
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: 20.0.2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-cp4a-operator
  template:
    metadata:
      labels:
        name: ibm-cp4a-operator
        app.kubernetes.io/instance: ibm-dba
        app.kubernetes.io/managed-by: ibm-dba
        app.kubernetes.io/name: ibm-dba
        release: 20.0.2
      annotations:
        productID: "5737-I23"
        productName: "IBM Cloud Pak for Automation"
        productVersion: "20.0.2"
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: true
      serviceAccountName: ibm-cp4a-operator
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 3
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - "amd64"
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          # Replace this with the built image name
          image: "cp.icr.io/cp/cp4a/icp4a-operator:20.0.2"
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            # Uncomment below for OCP 3.11
            # runAsUser: 1001
            capabilities:
              drop:
              - ALL
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          - mountPath: /opt/ansible/share
            name: operator-shared-folder
        - name: operator
          # Replace this with the built image name
          image: "cp.icr.io/cp/cp4a/icp4a-operator:20.0.2"
          imagePullPolicy: "IfNotPresent"
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -ec
              - |
                OLD_COUNT=$(cat /tmp/old) || true
                NEW_COUNT=$(find /tmp/ansible-operator/runner/icp4a.ibm.com/v1/ICP4ACluster | grep json -c) || true
                if [ $NEW_COUNT -eq 0 ]; then exit 0; fi
                echo $NEW_COUNT > /tmp/old
                if [ $NEW_COUNT -eq $OLD_COUNT ]; then exit 1;else exit 0; fi
            initialDelaySeconds: 100
            periodSeconds: 120
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            # Uncomment below for OCP 3.11
            # runAsUser: 1001
            capabilities:
              drop:
              - ALL
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          - mountPath: /opt/ansible/share
            name: operator-shared-folder
          args:
          - '--zap-time-encoding=iso8601'
          - '--zap-encoder=console'
          - "--max-workers"
          - "10"
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-cp4a-operator"
            - name: WORKER_ICP4ACLUSTER_ICP4A_IBM_COM
              value: "10"
            # MUST exist, used to accept baw license, valid value only can be "accept"
            - name: baw_license
              value:
            - name: delivery_type
              value: "baw"
      imagePullSecrets:
      - name: "admin.registrykey"
      volumes:
        - name: runner
          emptyDir: {}
        - name: "operator-shared-folder"
          persistentVolumeClaim:
            claimName: "operator-shared-pvc"
